config/routes.rb
Nekotter::Application.routes.draw do
  resources :nyans
  root to: "nyans#index"

  mount_sextant if Rails.env.development?
  match '*not_found' => 'errors#handle404'

end

app/models/nyan.rb
class Nyan
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :image, ImageUploader

  attr_accessible :title, :image, :image_cache, :remove_image
  field :title, type: String
  # validates_presence_of :title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nyans_controller.rb
class NyansController < ApplicationController
  # GET /nyans
  # GET /nyans.json
  def index
    @nyans = Nyan.order_by(:created_at.desc).all
    @nyan = Nyan.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nyans }
    end
  end

  # GET /nyans/1
  # GET /nyans/1.json
  def show
    @nyan = Nyan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nyan }
    end
  end

  # GET /nyans/new
  # GET /nyans/new.json
  def new
    @nyan = Nyan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nyan }
    end
  end

  # GET /nyans/1/edit
  def edit
    @nyan = Nyan.find(params[:id])
  end

  # POST /nyans
  # POST /nyans.json
  def create
    @nyan = Nyan.new(params[:nyan])
    respond_to do |format|
      if @nyan.save
        format.html { redirect_to @nyan, notice: 'Nyan was successfully created.' }
        format.json { render json: @nyan, status: :created, location: @nyan }
        format.js {
          html = render_to_string partial: 'pin', locals: { nyan: @nyan }
          render json: {data: @nyan, status: :created, html: html}
        }
      else
        format.html { render action: "new" }
        format.json { render json: @nyan.errors, status: :unprocessable_entity }
      end
    end

    # render json: {status: status, data: @nyan, html: html}
  end

  # PUT /nyans/1
  # PUT /nyans/1.json
  def update
    @nyan = Nyan.find(params[:id])

    respond_to do |format|
      if @nyan.update_attributes(params[:nyan])
        format.html { redirect_to @nyan, notice: 'Nyan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nyan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nyans/1
  # DELETE /nyans/1.json
  def destroy
    @nyan = Nyan.find(params[:id])
    @nyan.destroy

    render json: {status: 'success', nyan: @nyan}
    # respond_to do |format|
    #   format.html { redirect_to nyans_url }
    #   format.json { status: 'success', nyan: @nyan }
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nyans_helper.rb
module NyansHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Nekotter"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Nekotter
          .container.nav-collapse
            %ul.nav
              -# %li= link_to "Link 1", "/path1"
              -# %li= link_to "Link 2", "/path2"
              -# %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        -# .span3
        -#   .well.sidebar-nav
        -#     %ul.nav.nav-list
        -#       %li.nav-header Sidebar
        -#       %li= link_to "Link 1", "/path1"
        -#       %li= link_to "Link 2", "/path2"
        -#       %li= link_to "Link 3", "/path3"
        .span12
          = bootstrap_flash
          = yield

      -# %footer
      -#   %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/nyans/_form.html.haml
= simple_form_for @nyan, remote: true, html: { class: 'form-horizontal', id: 'nyan'} do |f|
  = f.input :title
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), nyans_path, class: => 'btn'

app/views/nyans/_pin.html.haml
.pin.nyan
  =image_tag nyan.image.thumb.url if nyan.image
  %p
    = link_to t("helpers.links.destroy"), nyan_path(nyan),
      method: :delete,
      remote: true,
      data: { confirm: t("helpers.links.confirm") },
      class: 'btn btn-mini btn-danger delete_nyan'

app/views/nyans/edit.html.haml
- model_class = Nyan
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/nyans/index.html.haml
- model_class = Nyan
.page-header
  %h1=t model_class.model_name.human.pluralize

%a.btn.btn-primary{"data-toggle" => "modal", href: "#form_nyan", role: "button"} New

#form_nyan.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Create
  = simple_form_for @nyan, remote: true, html: { class: 'form-horizontal', id: 'nyan'} do |f|
    .modal-body
      = f.input :title
      = f.input :image
    .modal-footer
      = f.button :submit, :class => 'btn-primary'
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
#wrapper
  #columns
    #nyans
      -@nyans.each do |nyan|
        =render 'pin', nyan: nyan

app/views/nyans/new.html.haml
- model_class = Nyan
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/nyans/show.html.haml
- model_class = Nyan
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = best_in_place @nyan, :title

- if @nyan.image?
  %p
    %strong= model_class.human_attribute_name(:image) + ':'
    %br
    = image_tag @nyan.image_url, class: 'img-polaroid'


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), nyans_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_nyan_path(@nyan), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), nyan_path(@nyan), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'